#
# -*- coding: utf-8 -*-
# This file is auto-generated by esapp/components/generate_components.py.
# Do not edit this file manually, as your changes will be overwritten.
#
# Transient Stability Field Constants for IDE Intellisense
#
# Usage:
#   from esapp.components import TS, Gen
#   wb.dyn.watch(Gen, [TS.Gen.P, TS.Gen.Speed])
#

from dataclasses import dataclass


@dataclass(frozen=True)
class TSField:
    """
    Represents a Transient Stability result field.

    Attributes:
        name: The PowerWorld field name string
        description: Human-readable description of the field

    """
    name: str
    description: str = ""

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"TSField({self.name!r})"

    def __getitem__(self, index: int) -> "TSField":
        """Allows accessing indexed fields like TS.Bus.Input[1]."""
        return TSField(f"{self.name}:{index}", self.description)


class TS:
    """
    Transient Stability Field Constants for Intellisense.

    Provides IDE autocomplete for all available TS result fields organized
    by object type (Bus, Gen, Branch, Load, Shunt, Area, etc.).

    Example:
        >>> from esapp.components import TS, Gen
        >>> wb.dyn.watch(Gen, [TS.Gen.P, TS.Gen.Speed, TS.Gen.Delta])
    """

    class Area:
        """TS result fields for Area objects."""
        ACE = TSField("TSAreaACE", "DSC::TSTimePointResult_TSAreaACE")
        AGCAble = TSField("TSAreaAGCAble", "")
        AreaSchedMW = TSField("TSAreaAreaSchedMW", "")
        AvgFreqHz = TSField("TSAreaAvgFreqHz", "Average Frequency (Hz)")
        Bias = TSField("TSAreaBias", "")
        Deadband = TSField("TSAreaDeadband", "")
        GICQ = TSField("TSAreaGICQ", "Total GIC Mvar Losses")
        GenAccP = TSField("TSAreaGenAccP", "Generator Accel MW Sum Area")
        GenMWLoss = TSField("TSAreaGenMWLoss", "DSC::TSTimePointResult_TSAreaGenMWLoss")
        GenP = TSField("TSAreaGenP", "Gen MW Sum Area")
        GenPMech = TSField("TSAreaGenPMech", "Generator Mech Input Sum Area")
        GenQ = TSField("TSAreaGenQ", "Gen Mvar Sum Area")
        IntP = TSField("TSAreaIntP", "Net MW interchange leaving the area")
        IntQ = TSField("TSAreaIntQ", "Net Mvar interchange leaving the area")
        LoadNPT = TSField("TSAreaLoadNPT", "Load MW Nominal Tripped")
        LoadP = TSField("TSAreaLoadP", "Load MW Sum Area")
        LoadQ = TSField("TSAreaLoadQ", "Load Mvar Sum Area")
        SchedMW = TSField("TSAreaSchedMW", "DSC::TSTimePointResult_TSAreaSchedMW")
        WeightAvgSpeed = TSField("TSAreaWeightAvgSpeed", "Weighted Average Speed of online synchronous machines (weighted by generator MVA Base)")

    class Branch:
        """TS result fields for Branch objects."""
        FromA = TSField("TSACLineFromA", "Current at From End in Amps")
        FromAinPU = TSField("TSACLineFromAinPU", "Current at From End in pu")
        FromAppImpR = TSField("TSACLineFromAppImpR", "Apparent Impedance Resistance at From End in pu")
        FromAppImpROhms = TSField("TSACLineFromAppImpROhms", "Apparent Impedance Resistance at From End in Ohms")
        FromAppImpX = TSField("TSACLineFromAppImpX", "Apparent Impedance Reactance at From End in pu")
        FromAppImpXOhms = TSField("TSACLineFromAppImpXOhms", "Apparent Impedance Reactance at From End in Ohms")
        FromAppImpZAng = TSField("TSACLineFromAppImpZAng", "Apparent Impedance Angle at From End")
        FromAppImpZMag = TSField("TSACLineFromAppImpZMag", "Apparent Impedance Magnitude at From End in pu")
        FromAppImpZMagOhms = TSField("TSACLineFromAppImpZMagOhms", "Apparent Impedance Magnitude at From End in Ohms")
        FromGIC = TSField("TSACLineFromGIC", "Per phase GIC flowing into the line/transformer at the from end, amps")
        FromP = TSField("TSACLineFromP", "MW at From End")
        FromQ = TSField("TSACLineFromQ", "Mvar at From End")
        FromS = TSField("TSACLineFromS", "MVA at From End")
        MinProfileVpu = TSField("TSACLineMinProfileVpu", "Minimum Profile Vpu")
        Percent = TSField("TSACLinePercent", "Flow Percentage of Contingency Limit (Result may be based on Amps or MVA depending on the Limit Monitoring Settings) ")
        RelayInput = TSField("TSACLineRelayInput", "")
        RelayOther = TSField("TSACLineRelayOther", "Other Fields of AC Line Relay/Other  1 (largest index is 10)")
        RelayStates = TSField("TSACLineRelayStates", "States of AC Line Relay/State  1 (largest index is 3)")
        Status = TSField("TSACLineStatus", "Status of line or transformer: 0 for open, 1 for closed")
        ToA = TSField("TSACLineToA", "Current at To End in amps")
        ToAinPU = TSField("TSACLineToAinPU", "Current at To End in pu")
        ToAppImpR = TSField("TSACLineToAppImpR", "Apparent Impedance Resistance at To End in pu")
        ToAppImpROhms = TSField("TSACLineToAppImpROhms", "Apparent Impedance Resistance at To End in Ohms")
        ToAppImpX = TSField("TSACLineToAppImpX", "Apparent Impedance Reactance at To End in pu")
        ToAppImpXOhms = TSField("TSACLineToAppImpXOhms", "Apparent Impedance Reactance at To End in Ohms")
        ToAppImpZAng = TSField("TSACLineToAppImpZAng", "Apparent Impedance Angle at To End")
        ToAppImpZMag = TSField("TSACLineToAppImpZMag", "Apparent Impedance Magnitude at To End in pu")
        ToAppImpZMagOhms = TSField("TSACLineToAppImpZMagOhms", "Apparent Impedance Magnitude at To End Ohms")
        ToGIC = TSField("TSACLineToGIC", "Per phase GIC flowing into the line/transformer at the to end, amps")
        ToP = TSField("TSACLineToP", "MW at To End")
        ToQ = TSField("TSACLineToQ", "Mvar at To End")
        ToS = TSField("TSACLineToS", "MVA at To End")

    class Bus:
        """TS result fields for Bus objects."""
        Deg = TSField("TSBusDeg", "Angle relative to angle reference (degrees)")
        DegNoshift = TSField("TSBusDegNoshift", "Angle, No Shift (degrees)")
        FreqMeasT = TSField("TSBusFreqMeasT", "Bus Frequency is calculated by taking the derivative of the bus angles in the system using this time delay")
        GenP = TSField("TSBusGenP", "Total Generator MW")
        GenQ = TSField("TSBusGenQ", "Total Generator Mvar")
        GroupFreqHz = TSField("TSBusGroupFreqHz", "")
        GroupLossP = TSField("TSBusGroupLossP", "")
        GroupLossQ = TSField("TSBusGroupLossQ", "")
        GroupSShuntP = TSField("TSBusGroupSShuntP", "")
        GroupSShuntQ = TSField("TSBusGroupSShuntQ", "")
        Input = TSField("TSBusInput", "Inputs of Bus/Input  1 (largest index is 10)")
        LoadP = TSField("TSBusLoadP", "Total Load MW")
        LoadQ = TSField("TSBusLoadQ", "Total Load Mvar")
        MinMaxFreq = TSField("TSBusMinMaxFreq", "Minimum value for the signal over the time window")
        MinMaxFreqTime = TSField("TSBusMinMaxFreqTime", "Time at which the minimum value over the time window is achieved")
        MinMaxVoltPU = TSField("TSBusMinMaxVoltPU", "Minimum Per Unit Voltage during simulation")
        MinMaxVoltPUTime = TSField("TSBusMinMaxVoltPUTime", "Time of Minimum Per Unit Voltage")
        Other = TSField("TSBusOther", "Other Fields of Bus/Other  1 (largest index is 10)")
        PairAngleDiff = TSField("TSBusPairAngleDiff", "DSC::TSTimePointResult_TSBusPairAngleDiff")
        ROCOFHz = TSField("TSBusROCOFHz", "Rate of Change of Frequency (ROCOF) in Hz/s")
        ROCOFHz_MISTAKE_FIXBUG_DONTUSE = TSField("TSBusROCOFHz_MISTAKE_FIXBUG_DONTUSE", "")
        Rad = TSField("TSBusRad", "Angle relative to angle reference (radians)")
        States = TSField("TSBusStates", "States of Bus/State  1 (largest index is 53)")
        Status = TSField("TSBusStatus", "Status of bus: 0 for open, 1 for energized")
        VPU = TSField("TSBusVPU", "Voltage Magnitude (pu)")
        VinKV = TSField("TSBusVinKV", "Voltage Magnitude (kV)")

    class Gen:
        """TS result fields for Gen objects."""
        AGCInput = TSField("TSGenAGCInput", "")
        AGCOther = TSField("TSGenAGCOther", "")
        AGCState = TSField("TSGenAGCState", "States of AGC Model/State  1 (largest index is 1)")
        AGCStatus = TSField("TSGenAGCStatus", "")
        AeroInput = TSField("TSGenAeroInput", "")
        AeroOther = TSField("TSGenAeroOther", "")
        AeroState = TSField("TSGenAeroState", "")
        AppImpR = TSField("TSGenAppImpR", "DSC::TSTimePointResult_TSGenAppImpR")
        AppImpX = TSField("TSGenAppImpX", "DSC::TSTimePointResult_TSGenAppImpX")
        Delta = TSField("TSGenDelta", "Rotor Angle relative to angle reference (degrees)")
        DeltaNoshift = TSField("TSGenDeltaNoshift", "Rotor Angle, No Shift (degrees)")
        EField = TSField("TSGenEField", "")
        ExciterInput = TSField("TSGenExciterInput", "Inputs of Exciter/Input  1 (largest index is 1)")
        ExciterName = TSField("TSGenExciterName", "Shows the name of the active exciter type for transient stability")
        ExciterOther = TSField("TSGenExciterOther", "Other Fields of Exciter/Other  1 (largest index is 8)")
        ExciterState = TSField("TSGenExciterState", "States of Exciter/State  1 (largest index is 20)")
        ExciterSubInterval2Used = TSField("TSGenExciterSubInterval2Used", "SubInterval Used, Exciter Model")
        FieldV = TSField("TSGenFieldV", "Field Voltage Magnitude (pu)")
        GEMVABase = TSField("TSGenGEMVABase", "")
        GovernorInput = TSField("TSGenGovernorInput", "Inputs of Governor/Input  1 (largest index is 1)")
        GovernorName = TSField("TSGenGovernorName", "Shows the name of the active governor type for transient stability")
        GovernorOther = TSField("TSGenGovernorOther", "Other Fields of Governor/Other  1 (largest index is 16)")
        GovernorState = TSField("TSGenGovernorState", "States of Governor/State  1 (largest index is 62)")
        GovernorSubInterval2Used = TSField("TSGenGovernorSubInterval2Used", "SubInterval Used, Governor Model")
        IPU = TSField("TSGenIPU", "Genrator current magnitude (pu)")
        Id = TSField("TSGenId", "d-q axis/Direct Axis Current [pu]")
        Ifd = TSField("TSGenIfd", "Field Current")
        Iq = TSField("TSGenIq", "d-q axis/Quadrature Axis Current [pu]")
        MWREf = TSField("TSGenMWREf", "MW reference value for the generator")
        MachineInput = TSField("TSGenMachineInput", "Inputs of Machine/Input  1 (largest index is 1)")
        MachineName = TSField("TSGenMachineName", "Shows the name of the active machine type for transient stability")
        MachineOther = TSField("TSGenMachineOther", "Other Fields of Machine/Other  1 (largest index is 14)")
        MachineState = TSField("TSGenMachineState", "States of Machine/State  1 (largest index is 15)")
        MachineSubInterval2Used = TSField("TSGenMachineSubInterval2Used", "SubInterval Used, Machine Model")
        MinMaxAngle = TSField("TSGenMinMaxAngle", "Maximum Angle Difference between internal machine angles during the simulation")
        MinMaxAngleTime = TSField("TSGenMinMaxAngleTime", "Simulation Time at which the Maximum Angle Difference between internal machine angles occurred during the simulation")
        MinMaxEfd = TSField("TSGenMinMaxEfd", "Minimum Field Voltage during simulation")
        MinMaxEfdTime = TSField("TSGenMinMaxEfdTime", "Time of Minimum Field Voltage")
        MinMaxFreq = TSField("TSGenMinMaxFreq", "Minimum Speed during simulation")
        MinMaxFreqTime = TSField("TSGenMinMaxFreqTime", "Time of Minimum Speed")
        MinMaxIfd = TSField("TSGenMinMaxIfd", "Minimum Field Current during simulation")
        MinMaxIfdTime = TSField("TSGenMinMaxIfdTime", "Time of Minimum Field Current")
        MinMaxPMech = TSField("TSGenMinMaxPMech", "Minimum Mechanical Power during simulation")
        MinMaxPMechTime = TSField("TSGenMinMaxPMechTime", "Time of Minimum Mechanical Power")
        MinMaxVs = TSField("TSGenMinMaxVs", "Minimum Stabilizer Vs during simulation")
        MinMaxVsTime = TSField("TSGenMinMaxVsTime", "Time of Minimum Stabilizer Vs")
        OELInput = TSField("TSGenOELInput", "")
        OELOther = TSField("TSGenOELOther", "DSC::TSTimePointResult_TSGenOELOther/Other  1 (largest index is 16)")
        OELState = TSField("TSGenOELState", "DSC::TSTimePointResult_TSGenOELState/State  1 (largest index is 24)")
        OtherName = TSField("TSGenOtherName", "Shows the name of the first other model type for transient stability")
        P = TSField("TSGenP", "MW injected by generator into its bus; this is after any transformer included as part of the generator model")
        PAirGap = TSField("TSGenPAirGap", "Airgap Power MW")
        PBus = TSField("TSGenPBus", "")
        PMech = TSField("TSGenPMech", "Mech Input")
        PauxCtrlInput = TSField("TSGenPauxCtrlInput", "DSC::TSTimePointResult_TSGenPauxCtrlInput/Input  1 (largest index is 2)")
        PauxCtrlOther = TSField("TSGenPauxCtrlOther", "DSC::TSTimePointResult_TSGenPauxCtrlOther/Other  1 (largest index is 5)")
        PauxCtrlState = TSField("TSGenPauxCtrlState", "DSC::TSTimePointResult_TSGenPauxCtrlState/State  1 (largest index is 10)")
        PlantCtrlInput = TSField("TSGenPlantCtrlInput", "Inputs of Plant Controller/Input  1 (largest index is 4)")
        PlantCtrlOther = TSField("TSGenPlantCtrlOther", "Other Fields of Plant Controller/Other  1 (largest index is 10)")
        PlantCtrlState = TSField("TSGenPlantCtrlState", "States of Plant Controller/State  1 (largest index is 27)")
        PlayIn = TSField("TSGenPlayIn", "")
        PrefCtrlInput = TSField("TSGenPrefCtrlInput", "")
        PrefCtrlOther = TSField("TSGenPrefCtrlOther", "Other Fields of Pref Controller such as Turbine Load Controller/Other  1 (largest index is 2)")
        PrefCtrlState = TSField("TSGenPrefCtrlState", "States of Pref Controller such as Turbine Load Controller/State  1 (largest index is 4)")
        Q = TSField("TSGenQ", "Mvar injected by generator into its bus; this is after any transformer included as part of the generator model")
        QBus = TSField("TSGenQBus", "")
        RelayInput = TSField("TSGenRelayInput", "")
        RelayOther = TSField("TSGenRelayOther", "Other Fields of Gen Relay/Other  1 (largest index is 16)")
        RelayState = TSField("TSGenRelayState", "States of Gen Relay/State  1 (largest index is 24)")
        S = TSField("TSGenS", "Power/Terminal MVA")
        SBus = TSField("TSGenSBus", "")
        SCLInput = TSField("TSGenSCLInput", "")
        SCLOther = TSField("TSGenSCLOther", "DSC::TSTimePointResult_TSGenSCLOther/Other  1 (largest index is 16)")
        SCLState = TSField("TSGenSCLState", "DSC::TSTimePointResult_TSGenSCLState/State  1 (largest index is 24)")
        SaveTwoBusEquiv = TSField("TSGenSaveTwoBusEquiv", "Save Two Bus Equivalent")
        StabilizerInput = TSField("TSGenStabilizerInput", "")
        StabilizerName = TSField("TSGenStabilizerName", "Shows the name of the active stabilizer type for transient stability")
        StabilizerOther = TSField("TSGenStabilizerOther", "Other Fields of Stabilizer/Other  1 (largest index is 2)")
        StabilizerState = TSField("TSGenStabilizerState", "States of Stabilizer/State  1 (largest index is 40)")
        StabilizerVs = TSField("TSGenStabilizerVs", "Stabilizer Vs")
        StabilzerSubInterval2Used = TSField("TSGenStabilzerSubInterval2Used", "SubInterval Used, Stabilizer Model")
        Status = TSField("TSGenStatus", "Status of generator: 0 for open, 1 for closed")
        TermVPU = TSField("TSGenTermVPU", "Terminal Voltage Magnitude (pu)")
        UELInput = TSField("TSGenUELInput", "")
        UELOther = TSField("TSGenUELOther", "DSC::TSTimePointResult_TSGenUELOther/Other  1 (largest index is 16)")
        UELState = TSField("TSGenUELState", "DSC::TSTimePointResult_TSGenUELState/State  1 (largest index is 24)")
        VOEL = TSField("TSGenVOEL", "Over-Excitation Limiter Signal")
        VSCL = TSField("TSGenVSCL", "DSC::TSTimePointResult_TSGenVSCL")
        VSCLOEL = TSField("TSGenVSCLOEL", "DSC::TSTimePointResult_TSGenVSCLOEL")
        VSCLUEL = TSField("TSGenVSCLUEL", "DSC::TSTimePointResult_TSGenVSCLUEL")
        VUEL = TSField("TSGenVUEL", "Under-Excitation Limiter Signal")
        Vd = TSField("TSGenVd", "d-q axis/Direct Axis Voltage [pu]")
        VoltPURef = TSField("TSGenVoltPURef", "Voltage setpoint for the generator (in per unit)")
        VperHz = TSField("TSGenVperHz", "Generator V per Hertz in pu.")
        Vq = TSField("TSGenVq", "d-q axis/Quadrature Axis Voltage [pu]")
        W = TSField("TSGenW", "Speed")

    class InjectionGroup:
        """TS result fields for InjectionGroup objects."""
        LoadNPT = TSField("TSInjectionGroupLoadNPT", "Load MW Nominal Tripped")
        P = TSField("TSInjectionGroupP", "MW at Injection Group")
        Pmech = TSField("TSInjectionGroupPmech", "Mech Input at Injection Group")
        Q = TSField("TSInjectionGroupQ", "Mvar at Injection Group")
        WARS = TSField("TSInjectionGroupWARS", "Weighted Average Rotor Speed. The formula is the sum of generator speed times Weight divided by sum of Weights. The intention is to set the Weights to be the H (Inertia) of the generators. The Weights are set in the Participation Factors of the injection group.")

    class Load:
        """TS result fields for Load objects."""
        Breaker = TSField("TSLoadBreaker", "Model Parameters/LoadBreaker")
        DistGenInput = TSField("TSLoadDistGenInput", "")
        DistGenOther = TSField("TSLoadDistGenOther", "Other Fields of Load Distributed Generation/Other  1 (largest index is 10)")
        DistGenP = TSField("TSLoadDistGenP", "Distributed Generation MW")
        DistGenQ = TSField("TSLoadDistGenQ", "Distributed Generation Mvar")
        DistGenStates = TSField("TSLoadDistGenStates", "States of Load Distributed Generation/State  1 (largest index is 10)")
        IAMPS = TSField("TSLoadIAMPS", "Load Current (amps)")
        IDeg = TSField("TSLoadIDeg", "Load Current Angle")
        IPU = TSField("TSLoadIPU", "Load Current (pu)")
        Input = TSField("TSLoadInput", "")
        NPT = TSField("TSLoadNPT", "MW Nominal Tripped")
        OnlyOrDistGenAndLoad = TSField("TSLoadOnlyOrDistGenAndLoad", "Set how the relay or event scaling will scale/affect the loads. The options are to affect Only Load MW and MVAR; or Dist Gen and Load MW and MVAR")
        Other = TSField("TSLoadOther", "Other Fields of Load/Other  1 (largest index is 36)")
        P = TSField("TSLoadP", "MW Load")
        Q = TSField("TSLoadQ", "Mvar Load")
        RelayInput = TSField("TSLoadRelayInput", "")
        RelayOther = TSField("TSLoadRelayOther", "")
        RelayStates = TSField("TSLoadRelayStates", "States of Load Relay/State  1 (largest index is 6)")
        S = TSField("TSLoadS", "MVA Load")
        Scalar = TSField("TSLoadScalar", "")
        Scalar_NotUsed = TSField("TSLoadScalar_NotUsed", "")
        States = TSField("TSLoadStates", "States of Load/State  1 (largest index is 20)")
        Status = TSField("TSLoadStatus", "Status of load: 0 for open, 1 for closed")
        VDeg = TSField("TSLoadVDeg", "Bus Voltage Angle (degrees)")
        VPU = TSField("TSLoadVPU", "Bus Voltage Magnitude (pu)")
        VinKV = TSField("TSLoadVinKV", "Bus Voltage Magnitude (kV)")

    class Shunt:
        """TS result fields for Shunt objects."""
        BusVPU = TSField("TSShuntBusVPU", "Bus Voltage Magnitude (pu)")
        BusVinKV = TSField("TSShuntBusVinKV", "Bus Voltage Magnitude (kV)")
        IAMPS = TSField("TSShuntIAMPS", "Switched current magnitude (amp)")
        IPU = TSField("TSShuntIPU", "Switched current magnitude (pu)")
        Input = TSField("TSShuntInput", "Inputs of Switched Shunt/Input  1 (largest index is 1)")
        Mvar = TSField("TSShuntMvar", "Actual Mvar")
        MvarinPU = TSField("TSShuntMvarinPU", "Actual Mvar in pu")
        NomMvar = TSField("TSShuntNomMvar", "Nominal Mvar")
        NomMvarinPU = TSField("TSShuntNomMvarinPU", "Nominal Mvar in pu")
        Other = TSField("TSShuntOther", "Other Fields of Switched Shunt/Other  1 (largest index is 1)")
        States = TSField("TSShuntStates", "States of Switched Shunt/State  1 (largest index is 20)")
        Status = TSField("TSShuntStatus", "Switched shunt status: 0 for open, 1 for closed")

    class Substation:
        """TS result fields for Substation objects."""
        AvgFreqHz = TSField("TSSubAvgFreqHz", "Average Frequency (Hz)")
        AvgPUVolt = TSField("TSSubAvgPUVolt", "Average Voltage (pu)")
        GICEFieldDeg = TSField("TSSubGICEFieldDeg", "GIC Efield Directions (degrees)")
        GICEFieldMag = TSField("TSSubGICEFieldMag", "GIC Efield Magnitude")
        GICIAmp = TSField("TSSubGICIAmp", "Total GIC (amps)")
        GICQ = TSField("TSSubGICQ", "Total GIC Mvar Losses")
        GenAccP = TSField("TSSubGenAccP", "Gen Acceleration MW Sum Substation")
        GenP = TSField("TSSubGenP", "Gen MW Sum Substation")
        GenPMech = TSField("TSSubGenPMech", "Generator Mech Input Sum Substation")
        GenQ = TSField("TSSubGenQ", "Gen Mvar Sum Substation")
        IntP = TSField("TSSubIntP", "")
        IntQ = TSField("TSSubIntQ", "")
        Intervals = TSField("TSSubIntervals", "Specify the number of sub-interval integration steps to use. A blank value will cause Simulator to use a default for that model type.  Normally a model will not use sub-interval integration. Values must be either blank, 1, 2, 4, 8, 16, 32, 64 or 128")
        LoadP = TSField("TSSubLoadP", "Load MW Sum Substation")
        LoadQ = TSField("TSSubLoadQ", "Load Mvar Sum Substation")
        MaxPUVolt = TSField("TSSubMaxPUVolt", "Maximum Voltage (pu)")
        MinPUOfHighestNomkV = TSField("TSSubMinPUOfHighestNomkV", "Lowest Voltage (pu) of Highest Nominal Voltage Buses")
        MinPUVolt = TSField("TSSubMinPUVolt", "Minimum Voltage (pu)")
        ROCOFHz = TSField("TSSubROCOFHz", "DSC::TSTimePointResult_TSSubROCOFHz")

    class System:
        """TS result fields for System objects."""
        DSMetric = TSField("TSSystemDSMetric", "DSC::PWCaseInformation_TSSystemDSMetric")
        GICQ = TSField("TSSystemGICQ", "Total GIC Mvar Losses")
        GICXFIeffmax = TSField("TSSystemGICXFIeffmax", "Maximum Transformer Per phase effective GIC for the transfomer in amps")
        GenAccP = TSField("TSSystemGenAccP", "Generator Accel MW Sum System")
        GenP = TSField("TSSystemGenP", "Gen MW Sum System")
        GenPMech = TSField("TSSystemGenPMech", "Generator Mech Input Sum System")
        GenQ = TSField("TSSystemGenQ", "Gen Mvar Sum System")
        LoadP = TSField("TSSystemLoadP", "Load MW Sum System")
        LoadQ = TSField("TSSystemLoadQ", "Load Mvar Sum System")
        UnservedLoadP = TSField("TSSystemUnservedLoadP", "Estimate of total system unserved load")

